// Pósters verificados (HTTP 200 + content-type imagen). null = usar fallback.
// Fuente: CDN de imágenes de TMDB (image.tmdb.org). Pósters a w500, hero a w1280.
// Verificado con: curl -sI -o /dev/null -w "%{http_code} %{content_type}"
const HERO_BG = "https://image.tmdb.org/t/p/w1280/pGFQCp12a8andfPlpnmXz44IIvY.jpg";   // imagen horizontal Vengadores (backdrop The Avengers 2012), o null
const POSTERS = {
  "Iron Man": "https://image.tmdb.org/t/p/w500/tFCTNx7foAsUQpgu2x1KjAJD1wT.jpg",
  "El Increíble Hulk": "https://image.tmdb.org/t/p/w500/p4NYZXVtgKf6aiH65QzzkUVJcsd.jpg",
  "Iron Man 2": "https://image.tmdb.org/t/p/w500/ayyJVOV5I4MGjti7nIHC3mVCagR.jpg",
  "Thor": "https://image.tmdb.org/t/p/w500/qFAVW4XJaxhj7PcpiUI5hhO9bOX.jpg",
  "Capitán América: El Primer Vengador": "https://image.tmdb.org/t/p/w500/82ucHZ4ioVGiweT1XMl1mUZaodq.jpg",
  "Los Vengadores": "https://image.tmdb.org/t/p/w500/ugX4WZJO3jEvTOerctAWJLinujo.jpg",
  "Iron Man 3": "https://image.tmdb.org/t/p/w500/cW0fOIZONkgeiMJDYzqUcgl4MUn.jpg",
  "Thor: El Mundo Oscuro": "https://image.tmdb.org/t/p/w500/gPAmH41VpK5UPaNhAiNJePzrL8z.jpg",
  "Capitán América: El Soldado de Invierno": "https://image.tmdb.org/t/p/w500/wP7JcCzpWlX5XeROpf4ox9ZVFT6.jpg",
  "Guardianes de la Galaxia": "https://image.tmdb.org/t/p/w500/zqZNnuMtrmK99Xux91KiCdnZxgb.jpg",
  "Vengadores: La Era de Ultrón": "https://image.tmdb.org/t/p/w500/71wSx6MQm8EbMNDi3vVaD8nD9SL.jpg",
  "Ant-Man": "https://image.tmdb.org/t/p/w500/zwuE28gSXlLFLgueqMe9b7xKy1f.jpg",
  "Capitán América: Civil War": "https://image.tmdb.org/t/p/w500/jPPy7tCfglppQo6J9nGwU6UmJ8X.jpg",
  "Doctor Strange": "https://image.tmdb.org/t/p/w500/wJEZI3PWyMW7qcW6n9jyCh7Cclf.jpg",
  "Guardianes de la Galaxia Vol. 2": "https://image.tmdb.org/t/p/w500/kdg6Y06jfq9FV7qknWNcKLYtBJn.jpg",
  "Spider-Man: Homecoming": "https://image.tmdb.org/t/p/w500/bRl6C6FwzTndk0MBGZZ68nRFlw3.jpg",
  "Thor: Ragnarok": "https://image.tmdb.org/t/p/w500/pGtkLdk4rnF2A3Yz2BHiTgRwMU4.jpg",
  "Black Panther": "https://image.tmdb.org/t/p/w500/lAPzezdc5E6DFnttJwCWXZ9A9C6.jpg",
  "Vengadores: Infinity War": "https://image.tmdb.org/t/p/w500/ksBQ4oHQDdJwND8H90ay8CbMihU.jpg",
  "Ant-Man y la Avispa": "https://image.tmdb.org/t/p/w500/bvYI6i9lQ3bsup9PgnMF3YYr8ZR.jpg",
  "Capitana Marvel": "https://image.tmdb.org/t/p/w500/5SPa7dZ85p54xa7E9tHRmfKq5ce.jpg",
  "Vengadores: Endgame": "https://image.tmdb.org/t/p/w500/br6krBFpaYmCSglLBWRuhui7tPc.jpg",
  "Spider-Man: Lejos de Casa": "https://image.tmdb.org/t/p/w500/o59zDVJDIehGcWZsMUGU5SN0V0D.jpg",
  "WandaVision": "https://image.tmdb.org/t/p/w500/j2VeSZ7tncd2p8z1CeMnxbxK76b.jpg",
  "Falcon y el Soldado de Invierno": "https://image.tmdb.org/t/p/w500/kW3vNNeeIDkZ2xoRyWmNkeOK6f1.jpg",
  "Loki (Temporada 1)": "https://image.tmdb.org/t/p/w500/53aonG0QS3ynbYuuwhPtyoOwTDD.jpg",
  "Black Widow": "https://image.tmdb.org/t/p/w500/uR3ex7LZrX3lbIMNb87WBXzCWM.jpg",
  "What If...? (Temporada 1)": "https://image.tmdb.org/t/p/w500/mTUd7Hl85FTq7Y7J0pGVIxNx9xr.jpg",
  "Shang-Chi y la Leyenda de los Diez Anillos": "https://image.tmdb.org/t/p/w500/9VqajJXm29uprSaxOcEh7O0d6E9.jpg",
  "Eternals": "https://image.tmdb.org/t/p/w500/zp85WEn9YKM3Cajk4m4ZDcbCHpp.jpg",
  "Hawkeye": "https://image.tmdb.org/t/p/w500/3ZcJetFxd8fwJ1I5xsLHCMTAKQo.jpg",
  "Spider-Man: No Way Home": "https://image.tmdb.org/t/p/w500/miZFgV81xG324rpUknQX8dtXuBl.jpg",
  "Moon Knight": "https://image.tmdb.org/t/p/w500/5AHnvXfW0mtsm047OP54n4pnV0R.jpg",
  "Doctor Strange en el Multiverso de la Locura": "https://image.tmdb.org/t/p/w500/1w3MlLZPqr2Pm5loQ9h2gJwenMr.jpg",
  "Ms. Marvel": "https://image.tmdb.org/t/p/w500/3KzoEdclGwXQH2t2oYZZlw46TvW.jpg",
  "Thor: Love and Thunder": "https://image.tmdb.org/t/p/w500/z9ajF6E39Hg2pXUofmUYgZHvdX.jpg",
  "She-Hulk: Abogada Hulka": "https://image.tmdb.org/t/p/w500/7jzX4ZKwDxHZP8uSXrDAkVTdvKe.jpg",
  "Werewolf by Night": "https://image.tmdb.org/t/p/w500/jCZ92sCQkHv8jHLI9Cz6ETuj0cS.jpg",
  "Black Panther: Wakanda Forever": "https://image.tmdb.org/t/p/w500/mYpT2R7639KvKZ668uoQGS2QNFp.jpg",
  "Guardianes de la Galaxia: Especial Felices Fiestas": "https://image.tmdb.org/t/p/w500/6vrO8wFlwJFI7hgN0rDt3WnZVrW.jpg",
  "Ant-Man y la Avispa: Quantumanía": "https://image.tmdb.org/t/p/w500/lKHy0ntGPdQeFwvNq8gK1D0anEr.jpg",
  "Guardianes de la Galaxia Vol. 3": "https://image.tmdb.org/t/p/w500/6GkKzdNosVAL7UGgwTtCHSxLQ67.jpg",
  "Secret Invasion": "https://image.tmdb.org/t/p/w500/jXLhr96JH5DG6TBM8rx8subMpnE.jpg",
  "Loki (Temporada 2)": "https://image.tmdb.org/t/p/w500/ksz8uiWczvz1TX28YOYE9WnS9RR.jpg",
  "The Marvels": "https://image.tmdb.org/t/p/w500/vpuuFM032yiX8tox4L84Wl9MGjG.jpg",
  "What If...? (Temporada 2)": "https://image.tmdb.org/t/p/w500/jI7Yddy1ii1xtCnVwinOhJEGD91.jpg",
  "Echo": "https://image.tmdb.org/t/p/w500/1RFLMSnFng8G23zZ1G5Q6lFVRfY.jpg",
  "Deadpool y Lobezno": "https://image.tmdb.org/t/p/w500/9TFSqghEHrlBMRR63yTx80Orxva.jpg",
  "Agatha All Along": "https://image.tmdb.org/t/p/w500/nbkbguUUNWQZygVJKjODyELBQk9.jpg",
  "What If...? (Temporada 3)": "https://image.tmdb.org/t/p/w500/jU5papp3tRvk8tHVugMHQC6uVyX.jpg",
  "Capitán América: Brave New World": "https://image.tmdb.org/t/p/w500/pVMSRyAiye7gZ8NtuCt1qgbspY9.jpg",
  "Daredevil: Born Again (Temporada 1)": "https://image.tmdb.org/t/p/w500/zNH50kOA5Zm5QSFqeIu3hJGuNdO.jpg",
  "Thunderbolts*": "https://image.tmdb.org/t/p/w500/yDWU8YyFkPnlVY627QXPvct8bz9.jpg",
  "Ironheart": "https://image.tmdb.org/t/p/w500/dOh6MJpdlQhYpLBhzhNQeYGKTZ5.jpg",
  "Los Cuatro Fantásticos: Primeros Pasos": "https://image.tmdb.org/t/p/w500/ckfiXWGEMWrUP53cc6QyHijLlhl.jpg",
  "Eyes of Wakanda": "https://image.tmdb.org/t/p/w500/rp3oUwY6K9mwz9VPFIDZzGyP66h.jpg",
  "Marvel Zombies": "https://image.tmdb.org/t/p/w500/5UbrwzZUR5lcoDds2phuahFHHhi.jpg",
  "Wonder Man": "https://image.tmdb.org/t/p/w500/6yy9nQlFt2l6UVWzrfhszFCaZ5C.jpg",
  "Daredevil: Born Again (Temporada 2)": "https://image.tmdb.org/t/p/w500/1jcGofudw0M2B9lqNy3GyeOf5uh.jpg",
  "Spider-Man: Brand New Day": "https://image.tmdb.org/t/p/w500/9g0sEFhmvmK4nGhXj8DHuv2noYI.jpg",
  "VisionQuest": "https://image.tmdb.org/t/p/w500/6j60tGRAjBmWRPTOEwhW6oRbPMP.jpg",
  "Vengadores: Doomsday": "https://image.tmdb.org/t/p/w500/rQKabpeIewLLNStFr3anEXI0xqu.jpg",
};
