// Pósters locales (descargados de TMDB). Clave = it.t del tracker.
const POSTERS_LOCAL = {
  "Iron Man": "assets/posters/iron-man.jpg",
  "El Increíble Hulk": "assets/posters/el-increible-hulk.jpg",
  "Iron Man 2": "assets/posters/iron-man-2.jpg",
  "Thor": "assets/posters/thor.jpg",
  "Capitán América: El Primer Vengador": "assets/posters/capitan-america-el-primer-vengador.jpg",
  "Los Vengadores": "assets/posters/los-vengadores.jpg",
  "Iron Man 3": "assets/posters/iron-man-3.jpg",
  "Thor: El Mundo Oscuro": "assets/posters/thor-el-mundo-oscuro.jpg",
  "Capitán América: El Soldado de Invierno": "assets/posters/capitan-america-el-soldado-de-invierno.jpg",
  "Guardianes de la Galaxia": "assets/posters/guardianes-de-la-galaxia.jpg",
  "Vengadores: La Era de Ultrón": "assets/posters/vengadores-la-era-de-ultron.jpg",
  "Ant-Man": "assets/posters/ant-man.jpg",
  "Capitán América: Civil War": "assets/posters/capitan-america-civil-war.jpg",
  "Doctor Strange": "assets/posters/doctor-strange.jpg",
  "Guardianes de la Galaxia Vol. 2": "assets/posters/guardianes-de-la-galaxia-vol-2.jpg",
  "Spider-Man: Homecoming": "assets/posters/spider-man-homecoming.jpg",
  "Thor: Ragnarok": "assets/posters/thor-ragnarok.jpg",
  "Black Panther": "assets/posters/black-panther.jpg",
  "Vengadores: Infinity War": "assets/posters/vengadores-infinity-war.jpg",
  "Ant-Man y la Avispa": "assets/posters/ant-man-y-la-avispa.jpg",
  "Capitana Marvel": "assets/posters/capitana-marvel.jpg",
  "Vengadores: Endgame": "assets/posters/vengadores-endgame.jpg",
  "Spider-Man: Lejos de Casa": "assets/posters/spider-man-lejos-de-casa.jpg",
  "WandaVision": "assets/posters/wandavision.jpg",
  "Falcon y el Soldado de Invierno": "assets/posters/falcon-y-el-soldado-de-invierno.jpg",
  "Loki (Temporada 1)": "assets/posters/loki-temporada-1.jpg",
  "Black Widow": "assets/posters/black-widow.jpg",
  "What If...? (Temporada 1)": "assets/posters/what-if-temporada-1.jpg",
  "Shang-Chi y la Leyenda de los Diez Anillos": "assets/posters/shang-chi-y-la-leyenda-de-los-diez-anillos.jpg",
  "Eternals": "assets/posters/eternals.jpg",
  "Hawkeye": "assets/posters/hawkeye.jpg",
  "Spider-Man: No Way Home": "assets/posters/spider-man-no-way-home.jpg",
  "Moon Knight": "assets/posters/moon-knight.jpg",
  "Doctor Strange en el Multiverso de la Locura": "assets/posters/doctor-strange-en-el-multiverso-de-la-locura.jpg",
  "Ms. Marvel": "assets/posters/ms-marvel.jpg",
  "Thor: Love and Thunder": "assets/posters/thor-love-and-thunder.jpg",
  "She-Hulk: Abogada Hulka": "assets/posters/she-hulk-abogada-hulka.jpg",
  "Werewolf by Night": "assets/posters/werewolf-by-night.jpg",
  "Black Panther: Wakanda Forever": "assets/posters/black-panther-wakanda-forever.jpg",
  "Guardianes de la Galaxia: Especial Felices Fiestas": "assets/posters/guardianes-de-la-galaxia-especial-felices-fiestas.jpg",
  "Ant-Man y la Avispa: Quantumanía": "assets/posters/ant-man-y-la-avispa-quantumania.jpg",
  "Guardianes de la Galaxia Vol. 3": "assets/posters/guardianes-de-la-galaxia-vol-3.jpg",
  "Secret Invasion": "assets/posters/secret-invasion.jpg",
  "Loki (Temporada 2)": "assets/posters/loki-temporada-2.jpg",
  "The Marvels": "assets/posters/the-marvels.jpg",
  "What If...? (Temporada 2)": "assets/posters/what-if-temporada-2.jpg",
  "Echo": "assets/posters/echo.jpg",
  "Deadpool y Lobezno": "assets/posters/deadpool-y-lobezno.jpg",
  "Agatha All Along": "assets/posters/agatha-all-along.jpg",
  "What If...? (Temporada 3)": "assets/posters/what-if-temporada-3.jpg",
  "Capitán América: Brave New World": "assets/posters/capitan-america-brave-new-world.jpg",
  "Daredevil: Born Again (Temporada 1)": "assets/posters/daredevil-born-again-temporada-1.jpg",
  "Thunderbolts*": "assets/posters/thunderbolts.jpg",
  "Ironheart": "assets/posters/ironheart.jpg",
  "Los Cuatro Fantásticos: Primeros Pasos": "assets/posters/los-cuatro-fantasticos-primeros-pasos.jpg",
  "Eyes of Wakanda": "assets/posters/eyes-of-wakanda.jpg",
  "Marvel Zombies": "assets/posters/marvel-zombies.jpg",
  "Wonder Man": "assets/posters/wonder-man.jpg",
  "Daredevil: Born Again (Temporada 2)": "assets/posters/daredevil-born-again-temporada-2.jpg",
  "Spider-Man: Brand New Day": "assets/posters/spider-man-brand-new-day.jpg",
  "VisionQuest": "assets/posters/visionquest.jpg",
  "Vengadores: Doomsday": "assets/posters/vengadores-doomsday.jpg",

  // Saga X-Men (pestaña "X-Men")
  "X-Men: La Serie Animada": "assets/posters/x-men-la-serie-animada.jpg",
  "X-Men": "assets/posters/x-men.jpg",
  "X-Men: Evolución": "assets/posters/x-men-evolucion.jpg",
  "X-Men 2": "assets/posters/x-men-2.jpg",
  "X-Men: La Decisión Final": "assets/posters/x-men-la-decision-final.jpg",
  "Lobezno y los X-Men": "assets/posters/lobezno-y-los-x-men.jpg",
  "X-Men Orígenes: Lobezno": "assets/posters/x-men-origenes-lobezno.jpg",
  "X-Men: Primera Generación": "assets/posters/x-men-primera-generacion.jpg",
  "Lobezno Inmortal": "assets/posters/lobezno-inmortal.jpg",
  "X-Men: Días del Futuro Pasado": "assets/posters/x-men-dias-del-futuro-pasado.jpg",
  "Deadpool": "assets/posters/deadpool.jpg",
  "X-Men: Apocalipsis": "assets/posters/x-men-apocalipsis.jpg",
  "Legion": "assets/posters/legion.jpg",
  "Logan": "assets/posters/logan.jpg",
  "The Gifted": "assets/posters/the-gifted.jpg",
  "Deadpool 2": "assets/posters/deadpool-2.jpg",
  "X-Men: Fénix Oscura": "assets/posters/x-men-fenix-oscura.jpg",
  "Los Nuevos Mutantes": "assets/posters/los-nuevos-mutantes.jpg",
  "X-Men '97": "assets/posters/x-men-97.jpg",
};
const HERO_LOCAL = "assets/fondo/endgame-backdrop.jpg";
